spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      client-id: test-client
      group-id: test-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer



server:
  port: 8088